export const SUPABASE_CONFIG = {
    URL: 'https://pxfucuiqtktgwspvpffh.supabase.co',
    // Verified working Legacy JWT Keys
    ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4ZnVjdWlxdGt0Z3dzcHZwZmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNjg4MzYsImV4cCI6MjA4MjY0NDgzNn0.gana8z6tVMvqXk7A_ejgGrnvYSvkA61Brzy7WMdwqeo',
    SERVICE_ROLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4ZnVjdWlxdGt0Z3dzcHZwZmZoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzA2ODgzNiwiZXhwIjoyMDgyNjQ0ODM2fQ.s6SpVC6nAQMoi9bdL7g5Nwg7UdxGlnqkHQ5OcyJH6uU'
};
